
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PAVILION
 */
public class hitung_nilai extends javax.swing.JFrame {

    /**
     * Creates new form hitung_nilai
     */
    public hitung_nilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nTugas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nQuiz = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nUTS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nUAS = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        kNilaiTugas = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        kNilaiQuiz = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        kNilaiUTS = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        kNilaiUAS = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        butNilaiTugas = new javax.swing.JButton();
        butNilaiQuiz = new javax.swing.JButton();
        butNilaiUTS = new javax.swing.JButton();
        butNilaiUAS = new javax.swing.JButton();
        butHitung = new javax.swing.JButton();
        butReset = new javax.swing.JButton();
        butKeluar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        hNama = new javax.swing.JLabel();
        hNim = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hNilaiTugas = new javax.swing.JLabel();
        hNilaiQuiz = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        hNilaiUTS = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        hNilaiUAS = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        hKetNilaiTugas = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        hKetNilaiQuiz = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        hKetNilaiUTS = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        hKetNilaiUAS = new javax.swing.JLabel();
        hasil = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ketHasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(280, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 55, 100));
        jLabel1.setText("HITUNG NILAI");

        jLabel2.setText("Nama");

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setToolTipText("");
        nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaFocusLost(evt);
            }
        });

        jLabel3.setText("NIM");

        nim.setBackground(new java.awt.Color(255, 255, 255));
        nim.setToolTipText("");
        nim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nimFocusLost(evt);
            }
        });
        nim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nimKeyTyped(evt);
            }
        });

        jLabel4.setText("____________________________________________________________________");

        jLabel5.setText("Nilai Tugas");

        nTugas.setBackground(new java.awt.Color(255, 255, 255));
        nTugas.setToolTipText("");
        nTugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nTugasKeyTyped(evt);
            }
        });

        jLabel6.setText("Nilai Quiz");

        nQuiz.setBackground(new java.awt.Color(255, 255, 255));
        nQuiz.setToolTipText("");
        nQuiz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nQuizKeyTyped(evt);
            }
        });

        jLabel7.setText("Nilai UTS");

        nUTS.setBackground(new java.awt.Color(255, 255, 255));
        nUTS.setToolTipText("");
        nUTS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nUTSKeyTyped(evt);
            }
        });

        jLabel8.setText("Nilai UAS");

        nUAS.setBackground(new java.awt.Color(255, 255, 255));
        nUAS.setToolTipText("");
        nUAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nUASKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        kNilaiTugas.setBackground(new java.awt.Color(0, 0, 0));
        kNilaiTugas.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kNilaiTugas.setForeground(new java.awt.Color(26, 179, 240));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kNilaiTugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel9.setText("Keterangan Nilai Tugas");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        kNilaiQuiz.setBackground(new java.awt.Color(0, 0, 0));
        kNilaiQuiz.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kNilaiQuiz.setForeground(new java.awt.Color(26, 179, 240));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kNilaiQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kNilaiQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel10.setText("Keterangan Nilai Quiz");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        kNilaiUTS.setBackground(new java.awt.Color(0, 0, 0));
        kNilaiUTS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kNilaiUTS.setForeground(new java.awt.Color(26, 179, 240));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        kNilaiUAS.setBackground(new java.awt.Color(0, 0, 0));
        kNilaiUAS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kNilaiUAS.setForeground(new java.awt.Color(26, 179, 240));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel12.setText("Keterangan Nilai UTS");

        jLabel13.setText("Keterangan Nilai UAS");

        butNilaiTugas.setText("+");
        butNilaiTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNilaiTugasActionPerformed(evt);
            }
        });

        butNilaiQuiz.setText("+");
        butNilaiQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNilaiQuizActionPerformed(evt);
            }
        });

        butNilaiUTS.setText("+");
        butNilaiUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNilaiUTSActionPerformed(evt);
            }
        });

        butNilaiUAS.setText("+");
        butNilaiUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNilaiUASActionPerformed(evt);
            }
        });

        butHitung.setText("HITUNG");
        butHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHitungActionPerformed(evt);
            }
        });

        butReset.setText("RESET");
        butReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResetActionPerformed(evt);
            }
        });

        butKeluar.setText("KELUAR");
        butKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKeluarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 55, 100));
        jLabel14.setText("HASIL NILAI");

        jLabel15.setForeground(new java.awt.Color(0, 55, 100));
        jLabel15.setText("Nama : ");

        jLabel16.setForeground(new java.awt.Color(0, 55, 100));
        jLabel16.setText("NIM :");

        hNama.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hNama.setForeground(new java.awt.Color(0, 55, 100));

        hNim.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hNim.setForeground(new java.awt.Color(0, 55, 100));

        jLabel17.setForeground(new java.awt.Color(0, 55, 100));
        jLabel17.setText("Nilai Tugas :");

        hNilaiTugas.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hNilaiTugas.setForeground(new java.awt.Color(0, 55, 100));

        hNilaiQuiz.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hNilaiQuiz.setForeground(new java.awt.Color(0, 55, 100));

        jLabel18.setForeground(new java.awt.Color(0, 55, 100));
        jLabel18.setText("Nilai Quiz :");

        jLabel19.setForeground(new java.awt.Color(0, 55, 100));
        jLabel19.setText("Nilai UTS :");

        hNilaiUTS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hNilaiUTS.setForeground(new java.awt.Color(0, 55, 100));

        jLabel20.setForeground(new java.awt.Color(0, 55, 100));
        jLabel20.setText("Nilai UAS :");

        hNilaiUAS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hNilaiUAS.setForeground(new java.awt.Color(0, 55, 100));

        jLabel21.setForeground(new java.awt.Color(0, 55, 100));
        jLabel21.setText("Keterangan");

        hKetNilaiTugas.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hKetNilaiTugas.setForeground(new java.awt.Color(0, 55, 100));

        jLabel22.setForeground(new java.awt.Color(0, 55, 100));
        jLabel22.setText("Keterangan");

        hKetNilaiQuiz.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hKetNilaiQuiz.setForeground(new java.awt.Color(0, 55, 100));

        jLabel23.setForeground(new java.awt.Color(0, 55, 100));
        jLabel23.setText("Keterangan");

        hKetNilaiUTS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hKetNilaiUTS.setForeground(new java.awt.Color(0, 55, 100));

        jLabel24.setForeground(new java.awt.Color(0, 55, 100));
        jLabel24.setText("Keterangan");

        hKetNilaiUAS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hKetNilaiUAS.setForeground(new java.awt.Color(0, 55, 100));

        hasil.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hasil.setForeground(new java.awt.Color(0, 55, 100));

        jLabel25.setForeground(new java.awt.Color(0, 55, 100));
        jLabel25.setText("HASIL : ");

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("___________________________________________");

        jLabel27.setForeground(new java.awt.Color(0, 55, 100));
        jLabel27.setText("KETERANGAN");

        ketHasil.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        ketHasil.setForeground(new java.awt.Color(0, 55, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(hNama)
                    .addComponent(hNim)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(185, 185, 185)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ketHasil, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(hNilaiTugas)
                                .addComponent(jLabel18)
                                .addComponent(hNilaiQuiz)
                                .addComponent(jLabel19)
                                .addComponent(hNilaiUTS)
                                .addComponent(jLabel20)
                                .addComponent(hNilaiUAS))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hKetNilaiTugas, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hKetNilaiQuiz, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hKetNilaiUTS, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hKetNilaiUAS, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addComponent(hasil)
                    .addComponent(jLabel26)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel14)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hNim)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hNilaiTugas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hNilaiQuiz)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hNilaiUTS)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hNilaiUAS)
                            .addComponent(hKetNilaiUAS)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hKetNilaiTugas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hKetNilaiQuiz)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hKetNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasil)
                    .addComponent(ketHasil))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nim, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nUAS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(nUTS, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                .addComponent(nTugas, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nQuiz, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butNilaiQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(butReset, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butHitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(butKeluar))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)))
                            .addComponent(butNilaiTugas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nQuiz)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nUTS)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(nUAS)
                                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(butNilaiUAS)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(butNilaiUTS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butNilaiQuiz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nTugasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nTugasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    evt.consume();
        }
    }//GEN-LAST:event_nTugasKeyTyped

    private void nQuizKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nQuizKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    evt.consume();
        }
    }//GEN-LAST:event_nQuizKeyTyped

    private void nUTSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nUTSKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    evt.consume();
        }
    }//GEN-LAST:event_nUTSKeyTyped

    private void nUASKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nUASKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    evt.consume();
        }
    }//GEN-LAST:event_nUASKeyTyped

    private void butNilaiTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNilaiTugasActionPerformed
        // TODO add your handling code here:
        String inpNilaiTugas = nTugas.getText();
        if( inpNilaiTugas.length() != 0){
            int nTugasINT = Integer.parseInt(nTugas.getText());
            if(nTugasINT >= 0 && nTugasINT <= 39){
                kNilaiTugas.setText("E");
                hNilaiTugas.setText(inpNilaiTugas);
                hKetNilaiTugas.setText("E");
            }else if(nTugasINT >= 40 && nTugasINT < 70){
                kNilaiTugas.setText("D");
                hNilaiTugas.setText(inpNilaiTugas);
                hKetNilaiTugas.setText("D");
            }else if(nTugasINT >= 70 && nTugasINT < 80){
                kNilaiTugas.setText("C");
                hNilaiTugas.setText(inpNilaiTugas);
                hKetNilaiTugas.setText("C");
            }else if(nTugasINT >= 80 && nTugasINT < 90){
                kNilaiTugas.setText("B");
                hNilaiTugas.setText(inpNilaiTugas);
                hKetNilaiTugas.setText("B");
            }else if(nTugasINT >= 90 && nTugasINT <= 100){
                kNilaiTugas.setText("A");
                hNilaiTugas.setText(inpNilaiTugas);
                hKetNilaiTugas.setText("A");
            }else{
                JOptionPane.showMessageDialog(null, "Masukkan nilai tugas 0 - 100");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nilai belum ditambahkan");
        }
    }//GEN-LAST:event_butNilaiTugasActionPerformed

    private void butNilaiQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNilaiQuizActionPerformed
        // TODO add your handling code here:
        String inpNilaiQuiz = nQuiz.getText();
        if( inpNilaiQuiz.length() != 0){
            int nQuizINT = Integer.parseInt(nQuiz.getText());
            if(nQuizINT >= 0 && nQuizINT <= 39){
                kNilaiQuiz.setText("E");
                hNilaiQuiz.setText(inpNilaiQuiz);
                hKetNilaiQuiz.setText("E");
            }else if(nQuizINT >= 40 && nQuizINT < 70){
                kNilaiQuiz.setText("D");
                hNilaiQuiz.setText(inpNilaiQuiz);
                hKetNilaiQuiz.setText("D");
            }else if(nQuizINT >= 70 && nQuizINT < 80){
                kNilaiQuiz.setText("C");
                hNilaiQuiz.setText(inpNilaiQuiz);
                hKetNilaiQuiz.setText("C");
            }else if(nQuizINT >= 80 && nQuizINT < 90){
                kNilaiQuiz.setText("B");
                hNilaiQuiz.setText(inpNilaiQuiz);
                hKetNilaiQuiz.setText("B");
            }else if(nQuizINT >= 90 && nQuizINT <= 100){
                kNilaiQuiz.setText("A");
                hNilaiQuiz.setText(inpNilaiQuiz);
                hKetNilaiQuiz.setText("A");
            }else{
                JOptionPane.showMessageDialog(null, "Masukkan nilai quiz 0 - 100");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nilai belum ditambahkan");
        }
    }//GEN-LAST:event_butNilaiQuizActionPerformed

    private void butNilaiUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNilaiUTSActionPerformed
        // TODO add your handling code here:
        String inpNilaiUTS = nUTS.getText();
        if( inpNilaiUTS.length() != 0){
            int nUTSINT = Integer.parseInt(nUTS.getText());
            if(nUTSINT >= 0 && nUTSINT <= 39){
                kNilaiUTS.setText("E");
                hNilaiUTS.setText(inpNilaiUTS);
                hKetNilaiUTS.setText("E");
            }else if(nUTSINT >= 40 && nUTSINT < 70){
                kNilaiUTS.setText("D");
                hNilaiUTS.setText(inpNilaiUTS);
                hKetNilaiUTS.setText("D");
            }else if(nUTSINT >= 70 && nUTSINT < 80){
                kNilaiUTS.setText("C");
                hNilaiUTS.setText(inpNilaiUTS);
                hKetNilaiUTS.setText("C");
            }else if(nUTSINT >= 80 && nUTSINT < 90){
                kNilaiUTS.setText("B");
                hNilaiUTS.setText(inpNilaiUTS);
                hKetNilaiUTS.setText("B");
            }else if(nUTSINT >= 90 && nUTSINT <= 100){
                kNilaiUTS.setText("A");
                hNilaiUTS.setText(inpNilaiUTS);
                hKetNilaiUTS.setText("A");
            }else{
                JOptionPane.showMessageDialog(null, "Masukkan nilai uts 0 - 100");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nilai belum ditambahkan");
        }
    }//GEN-LAST:event_butNilaiUTSActionPerformed

    private void butNilaiUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNilaiUASActionPerformed
        // TODO add your handling code here:
        String inpNilaiUAS = nUAS.getText();
        if( inpNilaiUAS.length() != 0){
            int nUASINT = Integer.parseInt(nUAS.getText());
            if(nUASINT >= 0 && nUASINT <= 39){
                kNilaiUAS.setText("E");
                hNilaiUAS.setText(inpNilaiUAS);
                hKetNilaiUAS.setText("E");
            }else if(nUASINT >= 40 && nUASINT < 70){
                kNilaiUAS.setText("D");
                hNilaiUAS.setText(inpNilaiUAS);
                hKetNilaiUAS.setText("D");
            }else if(nUASINT >= 70 && nUASINT < 80){
                kNilaiUAS.setText("C");
                hNilaiUAS.setText(inpNilaiUAS);
                hKetNilaiUAS.setText("C");
            }else if(nUASINT >= 80 && nUASINT < 90){
                kNilaiUAS.setText("B");
                hNilaiUAS.setText(inpNilaiUAS);
                hKetNilaiUAS.setText("B");
            }else if(nUASINT >= 90 && nUASINT <= 100){
                kNilaiUAS.setText("A");
                hNilaiUAS.setText(inpNilaiUAS);
                hKetNilaiUAS.setText("A");
            }else{
                JOptionPane.showMessageDialog(null, "Masukkan nilai uas 0 - 100");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nilai belum ditambahkan");
        }
    }//GEN-LAST:event_butNilaiUASActionPerformed

    private void butHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHitungActionPerformed
        // TODO add your handling code here:
         
         String tugas = nTugas.getText();
         String quiz = nQuiz.getText();
         String uts = nUTS.getText();
         String uas = nUAS.getText();
         
         if(tugas.length() != 0 &&
            quiz.length() != 0 &&
            uts.length() != 0 &&
            uas.length() != 0){
             
         
            int nTugasINT = Integer.parseInt(tugas);
            int nQuizINT = Integer.parseInt(quiz);
            int nUTSINT = Integer.parseInt(uts);
            int nUASINT = Integer.parseInt(uas);
            double resault = (nTugasINT + nQuizINT + nUTSINT + nUASINT) / 4 ;

            if(resault >= 0 && resault <= 39){
               ketHasil.setText("E");
               hasil.setText(Double.toString(resault));
            }else if(resault >= 40 && resault < 70){
               ketHasil.setText("D");
               hasil.setText(Double.toString(resault));
            }else if(resault >= 70 && resault < 80){
               ketHasil.setText("C");
               hasil.setText(Double.toString(resault));
            }else if(resault >= 80 && resault < 90){
               ketHasil.setText("B");
               hasil.setText(Double.toString(resault));
            }else if(resault >= 90 && resault <= 100){
               ketHasil.setText("A");
               hasil.setText(Double.toString(resault));
            }else{
               JOptionPane.showMessageDialog(null, "TIDAK LULUS");
            }
         }else{
             JOptionPane.showMessageDialog(null, "Lengkapi form terlebih dahulu");
         }
    }//GEN-LAST:event_butHitungActionPerformed

    private void butResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResetActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        nim.setText("");
        nTugas.setText("");
        nQuiz.setText("");
        nUTS.setText("");
        nUAS.setText("");
        kNilaiTugas.setText("");
        kNilaiQuiz.setText("");
        kNilaiUTS.setText("");
        kNilaiUTS.setText("");
        kNilaiUAS.setText("");
        hNama.setText("");
        hNim.setText("");
        hNilaiTugas.setText("");
        hNilaiQuiz.setText("");
        hNilaiUTS.setText("");
        hNilaiUAS.setText("");
        hKetNilaiTugas.setText("");
        hKetNilaiQuiz.setText("");
        hKetNilaiUTS.setText("");
        hKetNilaiUAS.setText("");
        hasil.setText("");
        ketHasil.setText("");
    }//GEN-LAST:event_butResetActionPerformed

    private void butKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_butKeluarActionPerformed

    private void nimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nimKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    evt.consume();
        }
    }//GEN-LAST:event_nimKeyTyped

    private void namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusLost
        // TODO add your handling code here:
        String inpNama = nama.getText();
        if(inpNama.length() != 0){            
            hNama.setText(inpNama);
        }else{
            JOptionPane.showMessageDialog(null, "Nama belum ditambahkan");
        }
    }//GEN-LAST:event_namaFocusLost

    private void nimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nimFocusLost
        // TODO add your handling code here:
        String inpNim = nim.getText();
        if(inpNim.length() != 0){            
            hNim.setText(inpNim);
        }else{
            JOptionPane.showMessageDialog(null, "Nim belum ditambahkan");
        }
    }//GEN-LAST:event_nimFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hitung_nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hitung_nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hitung_nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hitung_nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hitung_nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butHitung;
    private javax.swing.JButton butKeluar;
    private javax.swing.JButton butNilaiQuiz;
    private javax.swing.JButton butNilaiTugas;
    private javax.swing.JButton butNilaiUAS;
    private javax.swing.JButton butNilaiUTS;
    private javax.swing.JButton butReset;
    private javax.swing.JLabel hKetNilaiQuiz;
    private javax.swing.JLabel hKetNilaiTugas;
    private javax.swing.JLabel hKetNilaiUAS;
    private javax.swing.JLabel hKetNilaiUTS;
    private javax.swing.JLabel hNama;
    private javax.swing.JLabel hNilaiQuiz;
    private javax.swing.JLabel hNilaiTugas;
    private javax.swing.JLabel hNilaiUAS;
    private javax.swing.JLabel hNilaiUTS;
    private javax.swing.JLabel hNim;
    private javax.swing.JLabel hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel kNilaiQuiz;
    private javax.swing.JLabel kNilaiTugas;
    private javax.swing.JLabel kNilaiTugas1;
    private javax.swing.JLabel kNilaiUAS;
    private javax.swing.JLabel kNilaiUTS;
    private javax.swing.JLabel ketHasil;
    private javax.swing.JTextField nQuiz;
    private javax.swing.JTextField nTugas;
    private javax.swing.JTextField nUAS;
    private javax.swing.JTextField nUTS;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    // End of variables declaration//GEN-END:variables
}
